/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, ScraperHandler } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateScraperHandler(options?: Omit<(UseMutationOptions<(ScraperHandler | undefined), DefaultError, Prisma.ScraperHandlerCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerCreateArgs, DefaultError, ScraperHandler, true>('ScraperHandler', 'POST', `${endpoint}/scraperHandler/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyScraperHandler(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ScraperHandlerCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('ScraperHandler', 'POST', `${endpoint}/scraperHandler/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyScraperHandler<TArgs extends Prisma.ScraperHandlerFindManyArgs, TQueryFnData = Array<Prisma.ScraperHandlerGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findMany`, args, options, fetch);
}

export function useInfiniteFindManyScraperHandler<TArgs extends Prisma.ScraperHandlerFindManyArgs, TQueryFnData = Array<Prisma.ScraperHandlerGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findMany`, args, options, fetch);
}

export function useSuspenseFindManyScraperHandler<TArgs extends Prisma.ScraperHandlerFindManyArgs, TQueryFnData = Array<Prisma.ScraperHandlerGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyScraperHandler<TArgs extends Prisma.ScraperHandlerFindManyArgs, TQueryFnData = Array<Prisma.ScraperHandlerGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findMany`, args, options, fetch);
}

export function useFindUniqueScraperHandler<TArgs extends Prisma.ScraperHandlerFindUniqueArgs, TQueryFnData = Prisma.ScraperHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueScraperHandler<TArgs extends Prisma.ScraperHandlerFindUniqueArgs, TQueryFnData = Prisma.ScraperHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findUnique`, args, options, fetch);
}

export function useFindFirstScraperHandler<TArgs extends Prisma.ScraperHandlerFindFirstArgs, TQueryFnData = Prisma.ScraperHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstScraperHandler<TArgs extends Prisma.ScraperHandlerFindFirstArgs, TQueryFnData = Prisma.ScraperHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/findFirst`, args, options, fetch);
}

export function useUpdateScraperHandler(options?: Omit<(UseMutationOptions<(ScraperHandler | undefined), DefaultError, Prisma.ScraperHandlerUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerUpdateArgs, DefaultError, ScraperHandler, true>('ScraperHandler', 'PUT', `${endpoint}/scraperHandler/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyScraperHandler(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ScraperHandlerUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('ScraperHandler', 'PUT', `${endpoint}/scraperHandler/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertScraperHandler(options?: Omit<(UseMutationOptions<(ScraperHandler | undefined), DefaultError, Prisma.ScraperHandlerUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerUpsertArgs, DefaultError, ScraperHandler, true>('ScraperHandler', 'POST', `${endpoint}/scraperHandler/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteScraperHandler(options?: Omit<(UseMutationOptions<(ScraperHandler | undefined), DefaultError, Prisma.ScraperHandlerDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerDeleteArgs, DefaultError, ScraperHandler, true>('ScraperHandler', 'DELETE', `${endpoint}/scraperHandler/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, ScraperHandler, Prisma.ScraperHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyScraperHandler(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.ScraperHandlerDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.ScraperHandlerDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('ScraperHandler', 'DELETE', `${endpoint}/scraperHandler/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.ScraperHandlerDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.ScraperHandlerDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.ScraperHandlerDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateScraperHandler<TArgs extends Prisma.ScraperHandlerAggregateArgs, TQueryFnData = Prisma.GetScraperHandlerAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateScraperHandler<TArgs extends Prisma.ScraperHandlerAggregateArgs, TQueryFnData = Prisma.GetScraperHandlerAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/aggregate`, args, options, fetch);
}

export function useGroupByScraperHandler<TArgs extends Prisma.ScraperHandlerGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ScraperHandlerGroupByArgs['orderBy'] } : { orderBy?: Prisma.ScraperHandlerGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ScraperHandlerGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ScraperHandlerGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ScraperHandlerGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ScraperHandlerGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ScraperHandlerGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByScraperHandler<TArgs extends Prisma.ScraperHandlerGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.ScraperHandlerGroupByArgs['orderBy'] } : { orderBy?: Prisma.ScraperHandlerGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.ScraperHandlerGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.ScraperHandlerGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.ScraperHandlerGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.ScraperHandlerGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.ScraperHandlerGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/groupBy`, args, options, fetch);
}

export function useCountScraperHandler<TArgs extends Prisma.ScraperHandlerCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ScraperHandlerCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/count`, args, options, fetch);
}

export function useSuspenseCountScraperHandler<TArgs extends Prisma.ScraperHandlerCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.ScraperHandlerCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.ScraperHandlerCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('ScraperHandler', `${endpoint}/scraperHandler/count`, args, options, fetch);
}

export function useCheckScraperHandler<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; proffIndustryCodes?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('ScraperHandler', `${endpoint}/scraperHandler/check`, args, options, fetch);
}
