/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        emailHandler: {
            name: 'EmailHandler', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, emails: {
                    name: "emails",
                    type: "String",
                    isArray: true,
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        scraperHandler: {
            name: 'ScraperHandler', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, proffIndustryCodes: {
                    name: "proffIndustryCodes",
                    type: "ProffIndustryCode",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'proffIndustryCode',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        proffIndustryCode: {
            name: 'ProffIndustryCode', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, code: {
                    name: "code",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, proffIndustryCode: {
                    name: "proffIndustryCode",
                    type: "ScraperHandler",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'proffIndustryCodes',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "proffIndustryCodeId" },
                }, proffIndustryCodeId: {
                    name: "proffIndustryCodeId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'proffIndustryCode',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            },
        },
        scrapedCompanies: {
            name: 'ScrapedCompanies', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, companies: {
                    name: "companies",
                    type: "Company",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'scraper',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        company: {
            name: 'Company', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, organizationNumber: {
                    name: "organizationNumber",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, State: {
                    name: "State",
                    type: "String",
                    isOptional: true,
                }, address: {
                    name: "address",
                    type: "String",
                    isOptional: true,
                }, postalCode: {
                    name: "postalCode",
                    type: "String",
                    isOptional: true,
                }, city: {
                    name: "city",
                    type: "String",
                    isOptional: true,
                }, registeredDate: {
                    name: "registeredDate",
                    type: "String",
                    isOptional: true,
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, url: {
                    name: "url",
                    type: "String",
                    isOptional: true,
                }, CEO: {
                    name: "CEO",
                    type: "String",
                    isOptional: true,
                }, SNI: {
                    name: "SNI",
                    type: "String",
                    isOptional: true,
                }, isFavorite: {
                    name: "isFavorite",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, scraper: {
                    name: "scraper",
                    type: "ScrapedCompanies",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'companies',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "scraperId" },
                }, scraperId: {
                    name: "scraperId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'scraper',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, organizationNumber: {
                    name: "organizationNumber",
                    fields: ["organizationNumber"]
                },
            },
        },

    },
    deleteCascade: {

    },

};
export default metadata;
