/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, EmailHandler } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateEmailHandler(options?: Omit<(UseMutationOptions<(EmailHandler | undefined), DefaultError, Prisma.EmailHandlerCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerCreateArgs, DefaultError, EmailHandler, true>('EmailHandler', 'POST', `${endpoint}/emailHandler/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyEmailHandler(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.EmailHandlerCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('EmailHandler', 'POST', `${endpoint}/emailHandler/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyEmailHandler<TArgs extends Prisma.EmailHandlerFindManyArgs, TQueryFnData = Array<Prisma.EmailHandlerGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findMany`, args, options, fetch);
}

export function useInfiniteFindManyEmailHandler<TArgs extends Prisma.EmailHandlerFindManyArgs, TQueryFnData = Array<Prisma.EmailHandlerGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findMany`, args, options, fetch);
}

export function useSuspenseFindManyEmailHandler<TArgs extends Prisma.EmailHandlerFindManyArgs, TQueryFnData = Array<Prisma.EmailHandlerGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyEmailHandler<TArgs extends Prisma.EmailHandlerFindManyArgs, TQueryFnData = Array<Prisma.EmailHandlerGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findMany`, args, options, fetch);
}

export function useFindUniqueEmailHandler<TArgs extends Prisma.EmailHandlerFindUniqueArgs, TQueryFnData = Prisma.EmailHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueEmailHandler<TArgs extends Prisma.EmailHandlerFindUniqueArgs, TQueryFnData = Prisma.EmailHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findUnique`, args, options, fetch);
}

export function useFindFirstEmailHandler<TArgs extends Prisma.EmailHandlerFindFirstArgs, TQueryFnData = Prisma.EmailHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstEmailHandler<TArgs extends Prisma.EmailHandlerFindFirstArgs, TQueryFnData = Prisma.EmailHandlerGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/findFirst`, args, options, fetch);
}

export function useUpdateEmailHandler(options?: Omit<(UseMutationOptions<(EmailHandler | undefined), DefaultError, Prisma.EmailHandlerUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerUpdateArgs, DefaultError, EmailHandler, true>('EmailHandler', 'PUT', `${endpoint}/emailHandler/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyEmailHandler(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.EmailHandlerUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('EmailHandler', 'PUT', `${endpoint}/emailHandler/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertEmailHandler(options?: Omit<(UseMutationOptions<(EmailHandler | undefined), DefaultError, Prisma.EmailHandlerUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerUpsertArgs, DefaultError, EmailHandler, true>('EmailHandler', 'POST', `${endpoint}/emailHandler/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteEmailHandler(options?: Omit<(UseMutationOptions<(EmailHandler | undefined), DefaultError, Prisma.EmailHandlerDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerDeleteArgs, DefaultError, EmailHandler, true>('EmailHandler', 'DELETE', `${endpoint}/emailHandler/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmailHandler, Prisma.EmailHandlerGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyEmailHandler(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.EmailHandlerDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmailHandlerDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('EmailHandler', 'DELETE', `${endpoint}/emailHandler/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmailHandlerDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmailHandlerDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.EmailHandlerDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateEmailHandler<TArgs extends Prisma.EmailHandlerAggregateArgs, TQueryFnData = Prisma.GetEmailHandlerAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateEmailHandler<TArgs extends Prisma.EmailHandlerAggregateArgs, TQueryFnData = Prisma.GetEmailHandlerAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/aggregate`, args, options, fetch);
}

export function useGroupByEmailHandler<TArgs extends Prisma.EmailHandlerGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.EmailHandlerGroupByArgs['orderBy'] } : { orderBy?: Prisma.EmailHandlerGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.EmailHandlerGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.EmailHandlerGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.EmailHandlerGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.EmailHandlerGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.EmailHandlerGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByEmailHandler<TArgs extends Prisma.EmailHandlerGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.EmailHandlerGroupByArgs['orderBy'] } : { orderBy?: Prisma.EmailHandlerGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.EmailHandlerGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.EmailHandlerGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.EmailHandlerGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.EmailHandlerGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.EmailHandlerGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/groupBy`, args, options, fetch);
}

export function useCountEmailHandler<TArgs extends Prisma.EmailHandlerCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.EmailHandlerCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/count`, args, options, fetch);
}

export function useSuspenseCountEmailHandler<TArgs extends Prisma.EmailHandlerCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.EmailHandlerCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmailHandlerCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmailHandler', `${endpoint}/emailHandler/count`, args, options, fetch);
}

export function useCheckEmailHandler<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; emails?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('EmailHandler', `${endpoint}/emailHandler/check`, args, options, fetch);
}
